HewlettPackard/hpegl-vmaas-terraform-resources

Makefile, internal/acceptance_test/provider_test.go
Using env variable as path to root directory so there is not an issue when the tests are copied to the terraform-provider. Set in make acceptance command.
This is one possible solution to this issue but we would like your opinion on it. Do you think this is ok? Another solution that is being considered is to only have one env var that contains the path and the name of the env/config file that you would like to test to reduce the number of env vars.  eg. ../../prod    
We would then write some code to separate the path from the config file name.
Let us know your thoughts.
=> fix relative path issue in provider_test.go

examples/resources/hpegl_vmaas_router_firewall_rule_group/resource.tf, go.mod, go.sum, internal/cmp/client.go, internal/cmp/constants.go, internal/cmp/router_firewall_rule_group.go, internal/cmp/router_nat.go, internal/resources/constants.go, internal/resources/resource_router_firewall_rule_groups.go, pkg/resources/registration.go
```
manjuna@ubuntu:~/hpe-hcss/terraform$ TF_REATTACH_PROVIDERS='{"terraform.example.com/vmaas/hpegl":{"Protocol":"grpc","ProtocolVersion":5,"Pid":177855,"Test":true,"Addr":{"Network":"unix","String":"/tmp/plugin1746432112"}}}' terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "hpegl_vmaas_router_firewall_rule_group" "tf_router_firewall_rule_group" {
+ description   = "Router Firewall rule group created via terraform"
+ group_layer   = "LocalGatewayRules"
+ id            = (known after apply)
+ is_deprecated = (known after apply)
+ name          = "tf_router_firewall_group"
+ priority      = 120
+ router_id     = 59
} …
```
=> Terraform Resource changes for Router Firewall Groups

internal/acceptance_test/helper.go, pkg/atf/constants.go, pkg/constants/constants.go
Acceptance test will now runs with IAM as middleware. 
**This will be the default behaviour and recommended way to run acceptance test.**
User can create seperate `api_client` for acceptance or use existing `api_client`. 
Following environment variable should set to run acceptance test for VMaaS
```bash
export HPEGL_VMAAS_LOCATION=<<location>>
export HPEGL_VMAAS_SPACE_NAME=<<space>>
export HPEGL_IAM_SERVICE_URL=<iam_service_url>>
export HPEGL_TENANT_ID=<tenant_id>>
export HPEGL_USER_SECRET=<user_secret>>
export HPEGL_USER_ID=<user_id>>
```
You can skip IAM by setting env TF_ACC_MOCK_IAM (along with TF_ACC_CMP_SUBJECT and HPEGL_IAM_TOKEN), but this is not recommended.
=> Acceptance test now supports runs with use of IAM

internal/cmp/instance_helper.go, internal/resources/diffValidation/resource_instances.go
As the deletion of snapshot is not supported currently, this code handles runtime exceptions which could arise when user tries to delete the snapshot. It notifies the user at the terraform plan time itself.
=> [DE9021] Handle the case of snapshot deletion

internal/acceptance_test/helper.go, internal/cmp/cloud_folder.go, internal/cmp/domain.go, internal/cmp/instance_helper.go, internal/cmp/network_interface.go, internal/cmp/network_proxy.go, internal/cmp/router.go, pkg/atf/helper.go, pkg/utils/meta.go
Following Lint issues are fixed:
```
Makefile:69: warning: ignoring old recipe for target 'tools'
==> Checking source code against linters...
golangci-lint run ./...
internal/cmp/cloud_folder.go:41:9: Error return value of `d.Set` is not checked (errcheck)
d.Set("code", cf.ExternalID)
^
internal/cmp/domain.go:42:12: Error return value of `tftags.Set` is not checked (errcheck)
tftags.Set(d, domains.NetworkDomains[0])
^
internal/cmp/instance_helper.go:73:8: Error return value of `d.Set` is not checked (errcheck)
d.Set("layout_id", instance.Instance.Layout.ID)
^
internal/cmp/instance_helper.go:86:12: Error return value of `tftags.Set` is not checked (errcheck)
tftags.Set(d, tfInstance)
^
internal/cmp/instance_helper.go:545:7: Error return value of `d.Set` is not checked (errcheck) …
```
=>  Fix Lint issues

internal/resources/diffValidation/resource_instances.go, internal/resources/resource_instances_helper.go
* Requirement: 
1) Change in network should not recreate the existing instance. 
2) Also allow the change in primary network.
* Changes Made:
1) 1st requirement was already handled in some other PR ( by removing the force_new=true). 
2) 2nd requirement is handled by removing the diff Validation check on the primary network, which was put to check that the primary network is neither updated or deleted. (Note: The constraint that network block should be at least 1 ensures that the user does not remove all the networks. This ensures that 1 network exists and it will be considered as primary network).
=> [DE8379] Allow primary network updation

internal/cmp/router.go, internal/resources/diffValidation/constants.go, internal/resources/diffValidation/resourse_router.go, internal/utils/constants.go
as per NSX-T, we will not be able to update to BGP timers when BGP is enabled. BGP timers can only be updated by turning off global BGP and then update the BGP timers to different values and then enable bgp back.
this code change takes care of two things
1. When the user is creating a Tier0 router, user can enabled bgp and set the restart timers to default values. This is supported operation, if the user tries to use non default values during the creation, operation is not allowed when bgp is enabled.
2. When the user tries to update the existing data with the new restart timers values, operation is not supported. He needs to turn off the bgp and update the timers, then enable bgp again.
=> Tier0 Router fixes

golangci-lint-config.yaml, internal/acceptance_test/data_source_edge_cluster_test.go, internal/acceptance_test/helper.go, internal/cmp/instance_clone.go, internal/cmp/resource_network.go, internal/cmp/router.go, internal/resources/diffValidation/resource_instances.go, internal/resources/diffValidation/resourse_router.go, internal/utils/retry.go, pkg/atf/reader.go, pkg/utils/meta.go
We have fixed few of the lint issues reported by the hpegl-provider team.
Currently we are disabling the following. Going forward, we should be fixing these one by one.
- dupl
- predeclared
- paralleltest
- gocritic
- forcetypeassert
- ifshort
- exhaustivestruct
- cyclop.
- errorlint
- varnamelen 
- maintidx
- ireturn
=> Lint issues 

internal/cmp/instance_helper.go, internal/resources/diffValidation/resource_instances.go, internal/resources/resource_instances_helper.go
- Requirement: Change of plan should not recreate the existing instance.
Changes Made: 
1) Remove 'force new' option 
2) Earlier, change in volume also included the change in plan, so adding a separate option to change plan ( Note: If there is a change in volume then there is no need to separately run the change in plan code)
=> [DE8373] Plan reconfigure

internal/cmp/constants.go, internal/cmp/template.go
From 5.4.3, we need to pass `filterType=Synced` as a query param to get the Virtual Images.
=> [5.4.3]Adding the filterType=Synced for Virtual Images

acc-testcases/README.md, internal/acceptance_test/helper.go, pkg/client/client.go, pkg/constants/constants.go, pkg/resources/registration.go, pkg/utils/utils.go
The standard pattern for the hpegl Terraform provider is to
allow the API endpoint of a service to be configurable as a parameter
in the service section of the provider block of a Terraform config.
This changes brings the VMaaS provider in line with that pattern.
A sample Terraform config would now look like:
provider "hpegl" {
vmaas {
location   = var.location
space_name = var.space
api_url = "https://iac-vmaas.intg.hpedevops.net"
}
}
If not provided the api_url will default to the VMaaS production endpoint.
=> Add API_URL as schema parameter

internal/resources/resource_loadbalancer.go, templates/resources/vmaas_load_balancer.md.tmpl
---
layout: ""
page_title: "hpegl_vmaas_load_balancer Resource - vmaas-terraform-resources"
subcategory: "vmaas"
description: |-
loadbalancer resource facilitates creating, updating
and deleting NSX-T  Network Load Balancers.
---
-> Compatible version >= 5.4.6
loadbalancer resource facilitates creating, updating
and deleting NSX-T  Network Load Balancers.
`hpegl_vmaas_load_balancer` resource supports NSX-T Load Balancer creation.
```terraform
resource "hpegl_vmaas_load_balancer" "tf_lb" {
name        = "tf_loadbalancer"
description = "Loadbalancer created using tf"
enabled     = true
group_access {
all = true
}
config {
admin_state    = true
size           = "SMALL"
log_level      = "INFO"
tier1_gateways = data.hpegl_vmaas_router.tier1_router.provider_id
}
}
```
- `config` (Block List, …
=> US26069 : Documentation template for load balancer

internal/resources/resource_lb_monitors.go, internal/resources/schemas/lb_monitor_schemas.go, templates/resources/vmaas_load_balancer_monitor.md.tmpl
---
layout: ""
page_title: "hpegl_vmaas_load_balancer_monitor Resource - vmaas-terraform-resources"
subcategory: "vmaas"
description: |-
Loadbalancer Monitor resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Monitors.
---
-> Compatible version >= 5.4.6
Loadbalancer Monitor resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Monitors.
`hpegl_vmaas_load_balancer_monitor` resource supports NSX-T Load balancer Monitor creation.
For creating an NSX-T Load balancer Monitor, use the following examples.
```terraform
resource "hpegl_vmaas_load_balancer_monitor" "tf_HTTP_MONITOR" {
lb_id       = data.hpegl_vmaas_load_balancer.tf_lb.id
name        = "tf_HTTP_MONITOR"
description = "HTTP_MONITOR creating using tf"
type        = …
```
=> Documentation template for load balancer Monitor

internal/resources/resource_lb_pools.go, templates/resources/vmaas_load_balancer_pool.md.tmpl
---
layout: ""
page_title: "hpegl_vmaas_load_balancer_pool Resource - vmaas-terraform-resources"
subcategory: "vmaas"
description: |-
loadbalancer Pool resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Pools.
---
-> Compatible version >= 5.4.6
loadbalancer Pool resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Pools.
`hpegl_vmaas_load_balancer_pool` resource supports NSX-T Load Balancer Pool creation.
```terraform
resource "hpegl_vmaas_load_balancer_pool" "tf_POOL" {
lb_id              = data.hpegl_vmaas_load_balancer.tf_lb.id
name               = "tf_POOL"
description        = "POOL created using tf"
min_active_members = 1
algorithm          = "WEIGHTED_ROUND_ROBIN"
config {
snat_translation_type   = "LBSnatAutoMap" …
```
=> Documentation template for load balancer Pool

examples/resources/hpegl_vmaas_load_balancer_virtual_server/nsx_t_lb_virtual_server.tf, internal/resources/resource_lb_virtual_servers.go, internal/resources/schemas/lb_vs_schemas.go, templates/resources/vmaas_load_balancer_virtual_server.md.tmpl
---
layout: ""
page_title: "hpegl_vmaas_load_balancer_virtual_server Resource - vmaas-terraform-resources"
subcategory: "vmaas"
description: |-
loadbalancer Virtual Server resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Virtual Servers.
---
-> Compatible version >= 5.4.6
loadbalancer Virtual Server resource facilitates creating, updating
and deleting NSX-T Network Load Balancer Virtual Servers.
`hpegl_vmaas_load_balancer_virtual_server` resource supports NSX-T Load Balancer Virtual Server creation.
```terraform
resource "hpegl_vmaas_load_balancer_virtual_server" "tf_lb_virtual_server" {
lb_id       = data.hpegl_vmaas_load_balancer.tf_lb.id
name        = "tf_virtual-server"
description = "tf_virtual-server created by tf"
vip_address = "10.11.12.13"
vip_port …
```
=> Documentation template for load balancer Virtual Server

go.mod, go.sum, internal/cmp/instance_clone.go, internal/cmp/instance_helper.go
Some of morpheus instances returns string, so json.Number is used to handle those cases.
=> DE15825: Replaced int with json.Number

.github/workflows/dev-acc.yml, README.md, acc-dev-testcases/data-sources/load_balancer.yaml, acc-dev-testcases/data-sources/load_balancer_monitor.yaml, acc-dev-testcases/data-sources/load_balancer_pool.yaml, acc-dev-testcases/data-sources/load_balancer_profile.yaml, acc-dev-testcases/data-sources/load_balancer_ssl_ca_certs.yaml, acc-dev-testcases/resources/instance_clone.yaml, acc-dev-testcases/resources/load_balancer.yaml, acc-dev-testcases/resources/load_balancer_monitor-monitor_err.yaml, acc-dev-testcases/resources/load_balancer_monitor.yaml, acc-dev-testcases/resources/load_balancer_pool.yaml, acc-dev-testcases/resources/load_balancer_profile.yaml, acc-dev-testcases/resources/load_balancer_virtual_server.yaml
This PR adds dev testing, the tenant used is VMaaS CICD on Integ environment
=> Added Dev acceptance case

.github/parse_logs.py, .github/workflows/acc.yml, .github/workflows/cicd-dev-acc.yml, .github/workflows/cicd-prod-acc.yml, .github/workflows/dev-acc.yml, .github/workflows/reusable-dev-acc.yml, Makefile, acc-testcases/data-sources/network_type.yaml
This PR adds changes for dev acceptance testing workflow. Now user can run specific set of testcase for Dev testing. The terraform logs are attached as artifacts for further reference.
Additionally, CI CD workflow has been added to test all the dev acceptance test.
Note: Github actions doesn't allow any individual workflow to be longer than 6hrs, hence the testcases were broken down.
Test workflows:
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7276501128
https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/runs/7284337277
=> Include IaC testing for cicd

.github/workflows/acc.yml
Removed on schedule run, cause cicd triggers cicd-prod-acc.yml which is similar to acc.yml
Ref: https://github.com/hpe-hcss/vmaas-cmp-tests/pull/288 
New Schedule run Workflow: https://github.com/HewlettPackard/hpegl-vmaas-terraform-resources/actions/workflows/cicd-prod-acc.yml
Workflow Triggered by: https://github.com/hpe-hcss/vmaas-cmp-tests/actions/workflows/pce_solution_workflow.yml
=> Updated Acceptance Test

.github/workflows/acc.yml, .github/workflows/ci.yml, acc-dev-testcases/resources/network.yaml, acc-testcases/resources/network.yaml
=> Network testcase fix

templates/resources/vmaas_dhcp_server.md.tmpl, templates/resources/vmaas_instance.md.tmpl, templates/resources/vmaas_instance_clone.md.tmpl, templates/resources/vmaas_load_balancer.md.tmpl, templates/resources/vmaas_load_balancer_monitor.md.tmpl, templates/resources/vmaas_load_balancer_pool.md.tmpl, templates/resources/vmaas_load_balancer_profile.md.tmpl, templates/resources/vmaas_load_balancer_virtual_server.md.tmpl, templates/resources/vmaas_network.md.tmpl, templates/resources/vmaas_router.md.tmpl, templates/resources/vmaas_router_bgp_neighbor.tmpl, templates/resources/vmaas_router_firewall_rule_group.md.tmpl, templates/resources/vmaas_router_nat_rule.md.tmpl, templates/resources/vmaas_router_route.md.tmpl
We've updated the version of tfplugin-docs which has exposed issues with the existing resource templates.  As a result of a change in indentation in the generated "description" field of the the .md files resulting from the resource templates the documentation wasn't being categorised correctly on the provider registry landing page.  To fix this we make the following change in each template:
{{ .Description | plainmarkdown | trimspace | prefixlines "  " }}
becomes
{{ .Description | plainmarkdown | trimspace | prefixlines "  " }}
=> Fix-up docs templates

acc-dev-testcases/README.md, pkg/client/client.go, pkg/resources/registration.go
testing where certs are not added
ignore tls
=> Remove vmaas-api and add insecure flag
